apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: sample-policy
spec:
  images:
    - glob: "gcr.io/chainguard-demo/*"
    - glob: "ttl.sh/*"
    - glob: "ttl.sh/*/*"
    - glob: "index.docker.io/*"
    - glob: "index.docker.io/*/*"
  authorities:
    - keyless:
        url: https://fulcio.sigstore.dev
