apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ko-build-image
spec:
  params:
    - name: MAIN_DIR
      description: Directory containing the main executable (one with main func) to build.
    - name: KO_DOCKER_REPO
      description: Registry to push the image to
      type: string
      default: ghcr.io/chainguard-dev/tekton-demo
    - name: github-token-secret
      type: string
      description: name of the secret holding the github-token
      default: github-token
  results:
    - name: IMAGES
      description: Digest of the image just built.
  workspaces:
    - name: source
      description: Where the dependencies and source code are.
  steps:
    - name: ko-build-image
      image: ghcr.io/google/ko:latest
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.github-token-secret)
              key: GITHUB_TOKEN
        - name: KO_DOCKER_REPO
          value: $(params.KO_DOCKER_REPO)
        - name: GOMODCACHE
          value: $(workspaces.source.path)/gomod
      script: |
        cd $(workspaces.source.path)
        ko build --bare --sbom spdx-json $(params.MAIN_DIR) --tags $(git rev-parse --short HEAD) --image-refs=ko.images 
        
        echo "Image build: $(cat ko.images)"
        
        cat ko.images | tee /tekton/results/IMAGES
        
        cat /tekton/results/IMAGES
      volumeMounts:
        - name: oidc-info
          mountPath: /var/run/sigstore/cosign
  volumes:
    - name: oidc-info
      projected:
        sources:
          - serviceAccountToken:
              path: oidc-token
              expirationSeconds: 600 # Use as short-lived as possible.
              audience: sigstore
