apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-build-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: MAIN_DIR
      description: Directory containing the main executable (one with main func) to build.
    - name: KO_DOCKER_REPO
      description: Registry to push the image to
    - name: KOFILE
      description: Path to the .ko.yaml file to use when building with ko.
      default: ./.ko.yaml
    - name: COSIGN_REPOSITORY
      type: string
      default: "ghcr.io/chainguard-customers"
    - name: fulcio-endpoint
      description: Fulcio endpoint
      default: "https://fulcio.sigstore.dev"
    - name: rekor-endpoint
      description: Rekor endpoint
      default: "https://rekor.sigstore.dev"
  results:
    - name: IMAGE-DIGEST
      description: Digest of the image that was created
      value: $(tasks.source-to-image.results.DIGESTS)
  workspaces:
    - name: git-source
    - name: dependencies
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: git-source
    - name: install-dependencies
      runAfter:
      - fetch-from-git
      taskRef:
        name: install-go-dependencies
      workspaces:
        - name: source
          workspace: git-source
        - name: dependencies
          workspace: dependencies
    - name: source-to-image
      taskRef:
        name: ko-build-image
      runAfter:
        - install-dependencies
      workspaces:
        - name: source
          workspace: dependencies
      params:
        - name: KO_DOCKER_REPO
          value: $(params.KO_DOCKER_REPO)
        - name: MAIN_DIR
          value: $(params.MAIN_DIR)
    - name: sign-image
      taskRef:
        name: sign-image
      runAfter:
      - source-to-image
      params:
        - name: IMAGE
          value: $(tasks.source-to-image.results.DIGESTS)
        - name: COSIGN_REPOSITORY
          value: $(params.COSIGN_REPOSITORY)
        - name: dev.chainguard.refresher.rekor-endpoint
          value: $(params.rekor-endpoint)
        - name: dev.chainguard.refresher.fulcio-endpoint
          value: $(params.fulcio-endpoint)
    - name: trivy-scan
      taskRef:
        name: scan-trivy
      runAfter:
        - source-to-image
      params:
        - name: dev.chainguard.refresher.digest
          value: $(tasks.source-to-image.results.DIGESTS)
        - name: dev.chainguard.refresher.rekor-endpoint
          value: $(params.rekor-endpoint)
        - name: dev.chainguard.refresher.fulcio-endpoint
          value: $(params.fulcio-endpoint)