---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tuf-system
  name: tuf
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tuf
  namespace: tuf-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tuf
subjects:
- kind: ServiceAccount
  name: tuf
  namespace: tuf-system
