apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sign-image
spec:
  params:
  - name: IMAGE
    description: Image to sign
    type: string
  - name: COSIGN_REPOSITORY
    type: string
    default: ""
  - name: FULCIO_ENDPOINT
    type: string
    default: "https://fulcio.sigstore.dev"
  - name: REKOR_ENDPOINT
    type: string
    default: "https://rekor.sigstore.dev"
  steps:
  - name: sign
    image: gcr.io/projectsigstore/cosign:v1.13.0
    timeout: 2m
    args: [
      "sign",
      # Use workload identity to access images
      "--k8s-keychain",
      # Use the Rekor URL provided by the refresher.
      "--rekor-url", "$(params['REKOR_ENDPOINT'])",
      # Use the Fulcio URL provided by the refresher.
      "--fulcio-url", "$(params['FULCIO_ENDPOINT'])",
      "--force",
      "--allow-insecure-registry",
      "$(params['IMAGE'])",
    ]
    env:
    - name: COSIGN_EXPERIMENTAL
      value: "1"
    - name: COSIGN_REPOSITORY
      value: $(params["COSIGN_REPOSITORY"])
    volumeMounts:
    - name: oidc-info
      mountPath: /var/run/sigstore/cosign
  volumes:
  - name: oidc-info
    projected:
      sources:
        - serviceAccountToken:
            path: oidc-token
            expirationSeconds: 600 # Use as short-lived as possible.
            audience: sigstore
