apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scan-trivy
    # If you need to use a specific Service Account you can change this.
    # refresher.chainguard.dev/run-as: customer-builder
  labels:
    attestations.chainguard.dev/predicate-type: scan-trivy
spec:
  params:
  - name: digest
    type: string
  - name: target-registry
    type: string
    default: ""
  - name: COSIGN_REPOSITORY
    type: string
  - name: FULCIO_ENDPOINT
    type: string
    default: "https://fulcio.sigstore.dev"
  - name: REKOR_ENDPOINT
    type: string
    default: "https://rekor.sigstore.dev"
  steps:
  - name: test
    image: cgr.dev/chainguard/alpine-base:latest
    script: |
      cat /var/run/sigstore/cosign
    

  - name: trivyscan
    image: docker.io/aquasec/trivy:0.23.0
    command: ["trivy"]
    args: [
      "-q", "image",
      "-format", "json",
      "-o", "/workspace/image.trivy",
      "$(params['digest'])"
    ]

  - name: publish-scan-results
    image: gcr.io/projectsigstore/cosign:v1.13.0
    timeout: 10m
    args: [
      "attest",
      # Use workload identity to access images
      "--k8s-keychain",
      # Disable timeout (registry http fallback takes more than the default)
      "--timeout=0",
      # Force the upload
      "--force",
      # Use the Rekor URL provided by the refresher.
      "--rekor-url", "$(params['REKOR_ENDPOINT'])",
      # Use the Fulcio URL provided by the refresher.
      "--fulcio-url", "$(params['FULCIO_ENDPOINT'])",
      # Use the "predicate" produced by the previous step.
      "--predicate", "/workspace/image.trivy",
      "$(params['digest'])"
    ]
    env:
    - name: COSIGN_EXPERIMENTAL
      value: "1"
    - name: COSIGN_REPOSITORY
      value: $(params.COSIGN_REPOSITORY)
    volumeMounts:
    - name: oidc-info
      mountPath: /var/run/sigstore/cosign
  volumes:
  - name: oidc-info
    projected:
      sources:
        - serviceAccountToken:
            path: oidc-token
            expirationSeconds: 600 # Use as short-lived as possible.
            audience: sigstore